[package]
name = "builder"
version = "0.1.0"
authors = ["micah <micah@glowcoil.com>"]
edition = "2018"

[dependencies]
syntect = "4.5.0"
pulldown-cmark = "0.8.0"
toml = "0.7.3"
serde = { version = "1.0.160", features = ["derive"] }
chrono = "0.4.24"
